export interface MoodTheme {
  id: string
  name: string
  emoji: string
  primary: string
  secondary: string
  accent: string
  description: string
  quote: string
  gradientFrom: string
  gradientTo: string
  glowColor: string
}

export const moods: MoodTheme[] = [
  {
    id: 'happy',
    name: 'Happy',
    emoji: '😊',
    primary: '#FFD700',
    secondary: '#FFA500',
    accent: '#FF69B4',
    description: 'Energetic and vibrant',
    quote: 'Life is what you make it.',
    gradientFrom: 'from-yellow-400',
    gradientTo: 'to-orange-400',
    glowColor: '#FFD700',
  },
  {
    id: 'melancholy',
    name: 'Melancholy',
    emoji: '🌧',
    primary: '#4B7BA7',
    secondary: '#6B8FB8',
    accent: '#8A9CB8',
    description: 'Reflective and introspective',
    quote: 'In solitude, we find ourselves.',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-slate-600',
    glowColor: '#4B7BA7',
  },
  {
    id: 'calm',
    name: 'Calm',
    emoji: '🌙',
    primary: '#7C3AED',
    secondary: '#3B82F6',
    accent: '#60A5FA',
    description: 'Peaceful and serene',
    quote: 'Peace comes from within.',
    gradientFrom: 'from-purple-600',
    gradientTo: 'to-blue-600',
    glowColor: '#7C3AED',
  },
  {
    id: 'energetic',
    name: 'Energetic',
    emoji: '🔥',
    primary: '#DC2626',
    secondary: '#F97316',
    accent: '#FB923C',
    description: 'Intense and powerful',
    quote: 'Energy is everything.',
    gradientFrom: 'from-red-600',
    gradientTo: 'to-orange-600',
    glowColor: '#DC2626',
  },
  {
    id: 'focus',
    name: 'Focus',
    emoji: '⚡',
    primary: '#1E40AF',
    secondary: '#3B82F6',
    accent: '#0EA5E9',
    description: 'Concentrated and driven',
    quote: 'Focus creates magic.',
    gradientFrom: 'from-blue-900',
    gradientTo: 'to-cyan-600',
    glowColor: '#0EA5E9',
  },
  {
    id: 'dreamy',
    name: 'Dreamy',
    emoji: '🌌',
    primary: '#6D28D9',
    secondary: '#EC4899',
    accent: '#A78BFA',
    description: 'Imaginative and mystical',
    quote: 'Dreams are where possibilities live.',
    gradientFrom: 'from-indigo-600',
    gradientTo: 'to-pink-600',
    glowColor: '#A78BFA',
  },
  {
    id: 'nostalgic',
    name: 'Nostalgic',
    emoji: '🌧',
    primary: '#92400E',
    secondary: '#B45309',
    accent: '#D97706',
    description: 'Warm and timeless',
    quote: 'Yesterday echoes in today.',
    gradientFrom: 'from-amber-900',
    gradientTo: 'to-yellow-700',
    glowColor: '#D97706',
  },
  {
    id: 'romantic',
    name: 'Romantic',
    emoji: '❤️',
    primary: '#BE185D',
    secondary: '#EC4899',
    accent: '#F472B6',
    description: 'Tender and affectionate',
    quote: 'Love is the greatest melody.',
    gradientFrom: 'from-rose-700',
    gradientTo: 'to-pink-600',
    glowColor: '#F472B6',
  },
  {
    id: 'adventurous',
    name: 'Adventurous',
    emoji: '🚀',
    primary: '#15803D',
    secondary: '#16A34A',
    accent: '#4ADE80',
    description: 'Bold and exploratory',
    quote: 'Adventure awaits at every turn.',
    gradientFrom: 'from-green-700',
    gradientTo: 'to-emerald-600',
    glowColor: '#4ADE80',
  },
  {
    id: 'latenight',
    name: 'Late Night',
    emoji: '🎧',
    primary: '#1F2937',
    secondary: '#374151',
    accent: '#7C3AED',
    description: 'Dark and mysterious',
    quote: 'The night reveals what day hides.',
    gradientFrom: 'from-slate-900',
    gradientTo: 'to-purple-900',
    glowColor: '#7C3AED',
  },
]

export const musicCategories = [
  'Trending',
  'Hidden Gems',
  'Indie',
  'Hip-Hop',
  'Pop',
  'Rock',
  'Lo-fi',
  'EDM',
  'Classical',
  'Jazz',
  'R&B',
  'Punjabi',
  'Hindi',
  'Tamil',
  'Telugu',
  'Malayalam',
  'Bengali',
  'Marathi',
  'Nepali',
  'North Eastern',
  'Korean',
  'Japanese',
  'Anime',
  'Instrumental',
  'International',
]
